CREATE DATABASE school
CREATE TABLE People(
	PersonID INTEGER AUTOINCREMENT PRIMARY KEY,
	FullName TEXT NOT NULL,
	DateOfBirth TEXT NOT NULL,
	ScreenName TEXT NOT NULL,
	isAdult INTEGER NOT NULL
	)
	